import {StyleSheet} from 'react-native';
import {Colors} from 'utils/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  change: {
    fontSize: 18,
    fontFamily: 'RobotoSlab-Bold',
    color: '#756156',
  },
  headerShadow: {
    backgroundColor: Colors.background,
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.41,

    elevation: 2,
  },
  headerNoShadow: {
    backgroundColor: Colors.background,
    zIndex: 10,
  },
  textInputStyle: {
    borderBottomWidth: 1,
    borderColor: Colors.lighter,
    marginVertical: 10,
    marginLeft: 15,
    marginRight: 20,
    fontSize: 16,
    height: 40,
    color: Colors.foreground,
  },
  title: {
    fontSize: 35,
    fontFamily: 'RobotoSlab-Bold',
    color: Colors.foreground,
    marginTop: 0,
    marginLeft: 15,
    flex: 1,
  },
  balance: {
    fontSize: 17,
    fontFamily: 'RobotoSlab-Bold',
    fontWeight: 'bold',
    letterSpacing: -0.5,
    justifyContent: 'center',
    color: Colors.foreground,
    marginTop: 2,
    flex: 0.5,
    paddingRight: 16,
    textAlign: 'right',
    alignSelf: 'center',
  },
  subtitle: {
    fontSize: 16,
    fontFamily: 'RobotoSlab-Bold',
    color: Colors.lighter,
    marginVertical: 20,
    marginLeft: 15,
  },
  moreBtn: {
    paddingHorizontal: 5,
    justifyContent: 'space-around',
    paddingRight: 13,
  },
  pillsContainer: {
    marginHorizontal: 20,
    marginBottom: 20,
    marginTop: 15,
    flexDirection: 'row',
  },
  appButtonContainerSelected: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.pill,
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginRight: 5,
  },
  appButtonContainer: {
    alignSelf: 'flex-start',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginRight: 5,
  },
  subLeft: {
    fontSize: 15,
    fontFamily: 'RobotoSlab-Medium',
    color: Colors.lighter,
    marginBottom: 10,
    marginLeft: 10,
    marginTop: 10,
  },
  subRight: {
    fontSize: 15,
    fontFamily: 'RobotoSlab-Medium',
    color: Colors.lighter,
    marginBottom: 10,
    marginRight: 10,
    marginTop: 10,
  },
  appButtonText: {
    fontSize: 11,
    color: Colors.foreground,
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },
  close: {
    position: 'absolute',
    backgroundColor: Colors.background,
    width: 40,
    height: 40,
    left: 10,
    top: 10,
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
  },
  nftpills: {
    backgroundColor: Colors.darker,
    padding: 5,
    borderRadius: 20,
    paddingHorizontal: 10,
    marginRight: 5,
    borderWidth: 1,
    borderColor: Colors.pill,
  },
  opensea: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2081E2',
    alignContent: 'flex-start',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingRight: 15,
    borderRadius: 5,
    marginBottom: 30,
  },
  openseaLogo: {
    height: 25,
    width: 25,
  },
  openseaText: {color: 'white', fontSize: 13},
  paraFore: {
    height: 350,
  },
  paraContainer: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  nftTitleCont: {
    paddingHorizontal: 15,
    backgroundColor: Colors.darker,
    paddingVertical: 15,
  },
  date: {
    fontSize: 12,
    color: Colors.lighter,
    marginBottom: 5,
  },
  nftTitle: {
    fontSize: 23,
    color: Colors.foreground,
    // fontFamily: 'RobotoSlab-Bold',
    fontWeight: 'bold',
  },
  nftTitleDesc: {
    fontSize: 17,
    color: Colors.foreground,
    // fontFamily: 'RobotoSlab-Bold',
    fontWeight: 'bold',
    marginTop: 15,
  },
  nftDesc: {
    fontSize: 15,
    color: Colors.foreground,
    // fontFamily: 'RobotoSlab-Regular',
    marginTop: 10,
  },
  nftDesc2: {
    fontSize: 14,
    color: Colors.foreground,
    // fontFamily: 'RobotoSlab-Light',
    marginTop: 20,
  },
  nonft: {
    marginTop: -50,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  noNftImg: {
    height: 180,
    tintColor: 'gray',
    opacity: 0.4,
  },
  editContainer: {
    // height: 300,
    margin: 10,
    backgroundColor: Colors.background,
  },
  editTitle: {
    fontSize: 20,
    textAlign: 'center',
    marginTop: 25,
    fontFamily: 'RobotoSlab-Bold',
    color: Colors.foreground,
  },
  editInput: {
    color: 'black',
    backgroundColor: 'white',
    height: 45,
    width: '70%',
    borderRadius: 30,
    alignSelf: 'center',
    textAlign: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    fontSize: 17,
    marginVertical: 3,
  },
  modalsubtitle: {
    textAlign: 'center',
    fontSize: 14,
    color: Colors.lighter,
    marginBottom: 20,
    marginTop: 10,
  },
  modaldelete: {
    textAlign: 'center',
    fontSize: 13,
    color: Colors.red,
    marginBottom: 10,
    marginTop: 10,
  },
});
