const CONFIG = {};

process.env.TESTNET = false;

CONFIG.APP_VERSION = '1.1.0 (26)';
CONFIG.BUILD_NUMBER = 26;
CONFIG.TESTNET = process.env.TESTNET;
CONFIG.DEFAULT_DERIVATION_KEY = 0;
CONFIG.PIN_ANDROID_TIMEOUT = 180; // seconds
CONFIG.BALANCE_TIMEOUT = 10; // seconds
CONFIG.NEW_ASSET_DESCRIPTOR_VERSION = 1;
CONFIG.COVALENT_KEY = '';

export default CONFIG;
