import {LogBox} from 'react-native';

const CONFIG = {};

process.env.TESTNET = false;

LogBox.ignoreLogs(['Easing']);

CONFIG.APP_VERSION = '1.3.11 (80)';
CONFIG.BUILD_NUMBER_ANDROID = 80;
CONFIG.BUILD_NUMBER_IOS = 80;
CONFIG.TESTNET = process.env.TESTNET;
CONFIG.COINGRIG_KEY = '';
CONFIG.DEFAULT_DERIVATION_KEY = 0;
CONFIG.PIN_ANDROID_TIMEOUT = 180; // seconds
CONFIG.BALANCE_TIMEOUT = 15; // seconds
CONFIG.NEW_ASSET_DESCRIPTOR_VERSION = 1;
CONFIG.COVALENT_KEY = '';
CONFIG.MIGRATION_KEY = '@MIGRATION_KEY';
CONFIG.INIT_KEY = '@init';
CONFIG.ONESIGNAL_KEY = '';
CONFIG.ZAP_KEY = '';
CONFIG.SWAP_FEE = 0.005; // 0.5%
CONFIG.FEE_RECIPIENT = ''; // Ukraine donation address
CONFIG.AFFILIATE_ADDRESS = '';
CONFIG.BANKING_SANDBOX = __DEV__;
CONFIG.RAMP_KEY = '';
CONFIG.GUARDARIAN_KEY = '';
CONFIG.MIXPANEL_KEY = '';
CONFIG.OPENSEA_KEY = '';
CONFIG.MAX_REF_FEE = 1000;
// CONFIG.testNFTs = '0x092f83B8Ca7D0D7f1a2126758498CC01399551bD';

export default CONFIG;
