const apps = [
  {
    title: 'market.market',
    description: 'hub.market.descripton',
    screen: 'MarketScreen',
    backgroundImage: require('../../assets/hub/market.png'),
    keywords: 'market, piata, marche',
    enable: true,
    module: true,
  },
  {
    title: 'title.news',
    description: 'hub.news.description',
    screen: 'NewsScreen',
    backgroundImage: require('../../assets/hub/news.png'),
    keywords: 'stiri, news, nouvelles',
    enable: true,
    module: true,
  },
  {
    title: 'settings.walletconnect',
    description: 'hub.walletconnect.description',
    screen: 'WalletconnectScreen',
    backgroundImage: require('../../assets/hub/wc.png'),
    keywords: 'walletconnect',
    enable: true,
    module: true,
  },
  {
    title: 'Swap',
    screen: 'SwapScreen',
    backgroundImage: require('../../assets/hub/swap.png'),
    description: 'dashboard.coming_soon',
    keywords: 'swap, schimb, exchange',
    enable: false,
    module: true,
  },
  {
    title: 'Index invest',
    screen: 'IndexScreen',
    backgroundImage: require('../../assets/hub/invest.png'),
    description: 'dashboard.coming_soon',
    keywords: 'index, etf, invest',
    enable: false,
    module: true,
  },
  {
    title: 'Earn interest',
    screen: 'IndexScreen',
    backgroundImage: require('../../assets/hub/token.png'),
    description: 'dashboard.coming_soon',
    keywords: 'index, etf, invest',
    enable: false,
    module: true,
  },
  {
    title: 'Portfolio tracker',
    screen: 'NewsScreen',
    backgroundImage: require('../../assets/hub/track.png'),
    description: 'dashboard.coming_soon',
    keywords: 'portfolio, portofoliu, tracker',
    enable: false,
    module: true,
  },
  {
    title: 'Create token',
    screen: 'NewsScreen',
    backgroundImage: require('../../assets/hub/token.png'),
    description: 'dashboard.coming_soon',
    keywords: 'yoken, create, erc20',
    enable: false,
    module: true,
  },
  {
    title: 'Create NFT',
    screen: 'NewsScreen',
    backgroundImage: require('../../assets/hub/nft.png'),
    description: 'dashboard.coming_soon',
    keywords: 'create, nft',
    enable: false,
    module: true,
  },
  // {
  //   title: 'Coingecko',
  //   screen: 'https://coingecko.com',
  //   backgroundImage: require('../../assets/hub/nft.png'),
  //   description: 'Coingecko website',
  //   keywords: '-, -',
  //   enable: true,
  //   module: false,
  // },
];

export default apps;
