const apps = [
  {
    title: 'market.market',
    description: 'hub.market.descripton',
    screen: 'MarketScreen',
    backgroundImage: require('../../assets/hub/market.png'),
    enable: true,
    module: true,
  },
  {
    title: 'title.news',
    description: 'hub.news.description',
    screen: 'NewsScreen',
    backgroundImage: require('../../assets/hub/news.png'),
    enable: true,
    module: true,
  },
  {
    title: 'settings.walletconnect',
    description: 'hub.walletconnect.description',
    screen: 'WalletconnectScreen',
    backgroundImage: require('../../assets/hub/wc.png'),
    enable: true,
    module: true,
  },
  {
    title: 'Swap',
    screen: 'SwapScreen',
    backgroundImage: require('../../assets/hub/swap.png'),
    description: 'dashboard.coming_soon',
    enable: false,
    module: true,
  },
  {
    title: 'Portfolio tracker',
    screen: 'NewsScreen',
    backgroundImage: require('../../assets/hub/track.png'),
    description: 'dashboard.coming_soon',
    enable: false,
    module: true,
  },
  {
    title: 'Create token',
    screen: 'NewsScreen',
    backgroundImage: require('../../assets/hub/token.png'),
    description: 'dashboard.coming_soon',
    enable: false,
    module: true,
  },
  {
    title: 'Create NFT',
    screen: 'NewsScreen',
    backgroundImage: require('../../assets/hub/nft.png'),
    description: 'dashboard.coming_soon',
    enable: false,
    module: true,
  },
  {
    title: 'Coingecko',
    screen: 'https://coingecko.com',
    backgroundImage: require('../../assets/hub/nft.png'),
    description: 'Coingecko website',
    enable: true,
    module: false,
  },
];

export default apps;
